# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: abffcaca0dd8f6276b4f8b4773f0c47bfc3e1c37cc22cc74ea14f86f894bf60eefa1259c015f7e680af5f32404c885605562cc2f7b7165bdbd788b377f8babfe

test:
  secret_key_base: 8fccd832483fcfda1ee778902b8a1e8fa6ce81e191c0bf8ed481289b641dfa83fdab23dcf62ec8ed6c18dfa681c9ce7bae73fc49b252c484e260b7033a9eb6ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
